### ISSUE TITLE
Images do not appear

### ISSUE THREAD

**Issue by imo9van4** [Evgenii-Moskalev/Bootstrap-Grid#1]
wrong filepaths. Try:

on line 22:
`./img/Moskalev E.V..jpg`
on line 61:
`./img/jake-nackos-IF9TK5Uy-KI-unsplash.jpg`
on line 75:
`./img/imansyah-muhamad-putera-n4KewLKFOZw-unsplash.jpg`
etc

**Comment by Evgenii-Moskalev** [comment]
Fixed. Thank You!
